# Generated by Django 4.2.5 on 2023-09-06 21:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_newpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newpost',
            name='user_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
