# Generated by Django 4.2.5 on 2023-09-07 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_profile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newpost',
            name='post_text',
            field=models.CharField(blank=True, max_length=240, null=True),
        ),
    ]
