# Generated by Django 4.2.5 on 2023-09-07 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_alter_newpost_post_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newpost',
            name='post_text',
            field=models.CharField(max_length=240),
        ),
    ]
