# Generated by Django 4.2.5 on 2023-09-09 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0010_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
