# Generated by Django 4.2.5 on 2023-09-09 22:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0011_delete_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='newpost',
            name='likes',
            field=models.ManyToManyField(related_name='twitter_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
