# Generated by Django 4.2.5 on 2023-09-11 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0012_newpost_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newpost',
            name='likes',
        ),
    ]
