# Generated by Django 4.2.5 on 2023-09-11 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0014_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='newpost',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
