# Generated by Django 4.2.5 on 2023-09-11 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0015_newpost_likes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewPost',
            new_name='Post',
        ),
    ]
